---
apiVersion: v1
kind: Service
metadata:
    name: transactions-service
spec:
    selector:
        app: transactions-service
    ports:
        - protocol: "TCP"
          port: 8082
          targetPort: 8082
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: transactions-service
spec:
    selector:
        matchLabels:
            app: transactions-service
    replicas: 1
    template:
        metadata:
            labels:
                app: transactions-service
        spec:
            containers:
                - name: transactions-service
                  image: ninjakotka/transactions-service:latest
                  env:
                      - name: KAFKA_HOST
                        value: kafka-broker
                      - name: KAFKA_PORT
                        value: "9092"
                      - name: DB_HOST
                        value: mysql
                      - name: DB_PORT
                        value: "3306"
                      - name: DB_NAME
                        value: "coinbase"
                      - name: DB_USERNAME
                        value: "root"
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: password
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8082
